variables:
  BuildPlatform: x86
  BuildPlatformTranslated: '$(BuildPlatform)'
  PackageVersionOverride: ''
  WINOBJC_SDK_ROOT: '$(Build.SourcesDirectory)'

jobs:
  - job: build
    displayName: Build SDK

    strategy:
      matrix:
        #x86 Debug: { BuildPlatform: x86, BuildConfiguration: Debug }
        x86 Release: { BuildPlatform: x86, BuildConfiguration: Release }

    steps:
      - checkout: self
        clean: true
        lfs: true
        submodules: recursive

      - powershell: |-
          echo "##vso[task.setvariable variable=BuildPlatformTranslated]Win32"
        condition: eq(variables['BuildPlatform'], 'x86')
        displayName: Overcome BuildPlatform=x86 incongruity

      - task: NuGetToolInstaller@0
        displayName: Ensure NuGet 4.8.1
        inputs:
          versionSpec: 4.8.1

      - task: NuGetCommand@2
        displayName: Restore packages for tools.sln
        inputs:
          command: restore
          feedsToUse: config
          configPath: nuget.config
          restoreSolution: tools\tools.sln
          restoreDirectory: '$(Build.SourcesDirectory)\packages'

      - task: VSBuild@1
        displayName: Build tools.sln
        inputs:
          solution: tools\tools.sln
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
          msbuildArgs: >-
            /p:DeployExtension=false
            /p:PackageVersionOverride=$(PackageVersionOverride)

      - task: VSBuild@1
        displayName: Restore packages for build.sln
        inputs:
          solution: build\build.sln
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
          msbuildArgs: >-
            /t:Restore
            /p:BuildProjectReferences=false

      - task: VSBuild@1
        displayName: Build build.sln
        inputs:
          solution: build\build.sln
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
          msbuildArgs: >-
            /m
            /p:PackageVersionOverride=$(PackageVersionOverride)

      - task: PublishPipelineArtifact@0
        displayName: Publish tool packages
        inputs:
          artifactName: 'toolPackages-$(BuildPlatform)-$(BuildConfiguration)'
          targetPath: 'tools\OutputPackages\$(BuildConfiguration)'

      - task: PublishPipelineArtifact@0
        displayName: Publish framework packages
        inputs:
          artifactName: 'packages-$(BuildPlatform)-$(BuildConfiguration)'
          targetPath: 'build\OutputPackages\$(BuildConfiguration)'

      - powershell: |-
          Get-ChildItem build\$Env:BuildPlatformTranslated\ -Recurse -Include *.ilk,*.pdb,*.pri,*Lib.lib,*.res,*.iobj | Remove-Item -Force
        displayName: Clean outputs before test publication

      - task: PublishPipelineArtifact@0
        displayName: Publish WinObjC test assets
        inputs:
          artifactName: 'tests-$(BuildPlatform)-$(BuildConfiguration)'
          targetPath: 'build\$(BuildPlatformTranslated)\$(BuildConfiguration)\Universal Windows'

  - job: test
    displayName: Run SDK Tests
    dependsOn: build
    pool: Unprivileged Test Runners

    strategy:
      matrix:
        #x86 Debug: { BuildPlatform: x86, BuildConfiguration: Debug }
        x86 Release: { BuildPlatform: x86, BuildConfiguration: Release }

    steps:
      - checkout: self # The test scripts live in the repository, but we don't need LFS or anything.
        fetchDepth: 1
        clean: true
        lfs: false

      - powershell: |-
          echo "##vso[task.setvariable variable=BuildPlatformTranslated]Win32"
        condition: eq(variables['BuildPlatform'], 'x86')
        displayName: Overcome BuildPlatform=x86 incongruity

      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: 'tests-$(BuildPlatform)-$(BuildConfiguration)'
          targetPath: 'build\$(BuildPlatformTranslated)\$(BuildConfiguration)\Universal Windows'

      - task: PowerShell@2
        displayName: Run Tests for $(BuildPlatform) $(BuildConfiguration)
        inputs:
          targetType: filePath
          filePath: 'tests\Run-Tests.ps1'
          arguments: >-
            -ModuleFilter *Tests.dll
            -Platform $(BuildPlatformTranslated)
            -Config $(BuildConfiguration)

  - job: build_test_apps
    displayName: Build Test Apps
    dependsOn: test

    strategy:
      matrix:
        #x86 Debug: { BuildPlatform: x86, BuildConfiguration: Debug }
        x86 Release: { BuildPlatform: x86, BuildConfiguration: Release }

    steps:
      - checkout: self
        clean: true
        lfs: true

      - template: .ci/build-apps.yml
        parameters:
          rootDirectory: tests\testapps

      - powershell: |-
          New-Item -Type Directory _appx -EA:Ignore
          Get-ChildItem tests\testapps -r -include *.appx,*.appxbundle,*.appxsym | Copy-Item -Destination _appx

      - task: PublishPipelineArtifact@0
        displayName: Publish test apps
        inputs:
          artifactName: 'testApps-$(BuildPlatform)-$(BuildConfiguration)'
          targetPath: '_appx'


  - job: build_sample_apps
    displayName: Build Sample Apps
    dependsOn: test

    strategy:
      matrix:
        #x86 Debug: { BuildPlatform: x86, BuildConfiguration: Debug }
        x86 Release: { BuildPlatform: x86, BuildConfiguration: Release }

    steps:
      - checkout: self
        clean: true
        lfs: true

      - template: .ci/build-apps.yml
        parameters:
          rootDirectory: samples

      - powershell: |-
          New-Item -Type Directory _appx -EA:Ignore
          Get-ChildItem samples -r -include *.appx,*.appxbundle,*.appxsym | Copy-Item -Destination _appx

      - task: PublishPipelineArtifact@0
        displayName: Publish sample apps
        inputs:
          artifactName: 'sampleApps-$(BuildPlatform)-$(BuildConfiguration)'
          targetPath: '_appx'

